### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by Kikobeats**
screen shot 2017-08-12 at 16 34 31

Hello,

I love the project but I experimented problem used it, so let's go fix it.

- Added a fancy startup message
- Fixed configuration path file (https://github.com/dthree/mailit/issues/5)
- Added a little code convention (standard, prettier, and lint on each commit)

### CODE REVIEW

**Comment by dthree** [comment]
Hey, thanks!

I like the message box :)

-

I'm also a fan of prettier, however we should stick to the same config I'm using for my other REST API project, Addict. There's a few preferences, such as no semicolons, that I don't prefer.

https://github.com/dthree/addict/blob/master/lint-staged.config.js

Would you be able to update it to match this?

**Comment by Kikobeats** [comment]
I added standard as well, it uses single quote, what do you think about that?

**Comment by dthree** [comment]
That's good. The main point is that I want the two code styles to match, the main difference being semicolons.

**Comment by Kikobeats** [comment]
standard is one of the most popular linters:
https://github.com/standard/standard

in this PR you have a prettier + standard integration, so the code will be automagically formatted in each commit 😄 .

Honestly, semicolons are an unnecessary aesthetic detail

**Comment by dthree** [comment]
Really not in the mood for a holy war on code style. Please just respect the code style I use and prefer across my projects, if you want to merge this. I otherwise would love to add the merge.

**Comment by Kikobeats** [comment]
No problem; I can reverte the code style changes, but because you are not using one, is difficult to determinate the expected output for that.

**Comment by dthree** [comment]
Why don't we make this two separate PRs? I would love to merge in the startup message.

**Comment by Kikobeats** [comment]
@dthree Hey, I moved the startup message and the rest of development features into a separate package that you can use with Express like apps:

https://github.com/Kikobeats/svr

**Pull request closed without merging**
